version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - path/to/project/root:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
#    depends_on:
#      - db
#  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=pswd
#      - POSTGRES_DB=dbname
#
#volumes:
#  postgres_data: